[build-system]

requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "zombuild"
description = "a build system for project zomboid mods"
readme = "README.MD"
license = "AGPL-3.0-or-later"
requires-python = ">=3.14"
dependencies = ["pydantic~=2.12.5", "colorama~=0.4.6"]

dynamic = ["version"]

[project.scripts]
zombuild = "zombuild:main"

[tool.setuptools.dynamic]
version = { attr = "zombuild.__version__" }

[tool.black]
line-length = 90
