[project]
name = "zombuild"
version = "0.1.2"
description = "modula build system for project zomboid"
authors = [{ name = "Chris Bode" }]
license = "AGPL-3.0-or-later"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["pydantic (>=2.12.5,<3.0.0)", "colorama (>=0.4.6,<0.5.0)"]

scripts = { zombuild = "zombuild:main" }


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
    { include = "zombuild" },
    { include = "zombuild_core" },
    { include = "zombuild_codegen" },
]


[tool.ruff]

line-length = 88
target-version = "py314"

[tool.ruff.format]

skip-magic-trailing-comma = false
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.ruff.lint]
# Select rules that mirror Black's philosophy
select = ["E", "F", "W", "I"] # Pyflakes, Error, Warning, Isort
ignore = []

[tool.ruff.lint.isort]
force-single-line = true

[dependency-groups]
dev = ["pre-commit (>=4.5.1,<5.0.0)", "ruff (>=0.15.10,<0.16.0)"]
